version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
      - .:/var/www/html
    ports:
      - 8100:80
    links:
      - php-fpm

  php-fpm:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    expose:
      - 9000

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin124
      MYSQL_DATABASE: taskManage
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin124
    ports:
      - "9906:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: db

volumes:
  mysql-data:
